### ISSUE TITLE
How to show the randstrobemer from python?

### ISSUE THREAD

**Issue by yaowei2010** [ksahlin/strobemers#16]
Hello, I am so interesting on your algorithms.

Here, I have a question when I using your code.

I have tried your StrobeMap and it works. However, I would like to know about the randstrobes and what it could be generated by python. So, I found the indexing.py in your github repository. Here, the parameters "seq", I guess that it is not the formal FASTQ or FASTA files. If the parameters "seq" is transformed by the function "readfq" from from https://github.com/lh3/readfq/blob/master/readfq.py ? I would like to have a example to do this. Thanks.

**Comment by ksahlin** [comment]
Hi @yaowei2010,

`seq` is a string object in python. You can compute them from e.g., a fasta/fastq file with the function you mention as below code, where `fastq_file_path` is the path to your fasta/fastq file.

```
from modules import indexing

all_mers = defaultdict(list)

for acc, seq, qual in readfq(open(fastq_file_path, 'r')):
  for (p1,p2,p3), h in indexing.randstrobes(seq, k_size, w_min, w_max, order = 3).items():
    # all_mers is a dictionary with hash values as keys and 
    # a list with position-tuples of where the strobemer is sampled from
    all_mers[h].append( (p1,p2,p3) )  
    
```

**Comment by yaowei2010** [comment]
Thanks. It works.

I have used your script and made an example for me.
I tried to defined the minimizers on our sequences (150bp - 300bp), I cannot understand why there is order =2 or 3, and the numbers of strobemer results from each sequence are differents. I would like to know why. And could I change the seed in the randstrobe function? 

Another question is that if I generate the strobemers, how can I use them like StrobeMap on mapping?
Thank you for your suggestion.

This is my parameters I used for testing:

```
  inputfile = args.input
  form = args.format
  n, slen, qlen = 0, 0, 0
  all_mers = defaultdict(list)
  k_size = 12
  w_min = 10
  w_max = 100
  w = 100
 
  for name, seq, qual in readfq(fp):
      print(name)
      print(seq)
      # Order = 2
      #for (p1,p2), s in indexing.randstrobes_iter(seq, k_size, w_min, w_max, w = w,order = 2, buffer_size = 1000000):
      #    print((s, p1,p2))
      #    all_mers[s].append( (p1,p2) ) 
      # Order = 3
      for (p1,p2,p3), h in indexing.randstrobes(seq, k_size, w_min, w_max, w = 60, order = 3).items():
          print((h, p1, p2, p3))
          all_mers[h].append( (p1,p2,p3) )
```
And here is my result:
![image](https://github.com/user-attachments/assets/3d80a9d9-e0aa-43c6-949c-e4e32a846d0b)

**Comment by ksahlin** [comment]
>  I cannot understand why there is order =2 or 3, and the numbers of strobemer results from each sequence are differents.

order=2 returns strobemers with two strobes, hence two positions p1 and p2, while order=3 returns strobemers with three strobes, hence three positions of the strobes p1,p2 and p3.

> And could I change the seed in the randstrobe function?

If you mean the `prime` variable, then yes you can change it.

> Another question is that if I generate the strobemers, how can I use them like StrobeMap on mapping?

It's too broad of a question :)  You can for example read up on how seeding works in sequence mapping. Have a look at this paper https://genomebiology.biomedcentral.com/articles/10.1186/s13059-022-02831-7 or this video: https://www.youtube.com/watch?v=cn32telW63w

**Comment by yaowei2010** [comment]
Thank your suggestion, I know the p1, p2, and p3 were resulted from the order paramers. But in my case is the outcome of the strobemers were 9 strobemers with order 2. I would like to know where these were generated from the window size or not. And why is 9 per sequences (fasta). Thanks

**Comment by ksahlin** [comment]
I would have to know how your reads look like to know what is going on. If you send your first reads I can have a look. The read length and window parameters affect how many strobemers are generated. 

Note that the code you pasted above doesn't work because `fp` is not defined, you need to call `readfq(open(inputfile, 'r'))`.

**Comment by yaowei2010** [comment]
Ok I got your point now.  If I using these strobemers from fasta files to align fastq reads, should I also mark the strobemer pattern on my fastq reads? 

The following is my script I used:

```
import sys
import gzip
import argparse
from collections import defaultdict, deque
from fractions import Fraction
from typing import Iterator
from modules import indexing


def readfq(fp): # this is a generator function
    last = None # this is a buffer keeping the last unprocessed line
    while True: # mimic closure; is it a bad idea?
        if not last: # the first record or a record following a fastq
            for l in fp: # search for the start of the next record
                if l[0] in '>@': # fasta/q header line
                    last = l[:-1] # save this line
                    break
        if not last: break
        name, seqs, last = last[1:].partition(" ")[0], [], None
        for l in fp: # read the sequence
            if l[0] in '@+>':
                last = l[:-1]
                break
            seqs.append(l[:-1])
        if not last or last[0] != '+': # this is a fasta record
            yield name, ''.join(seqs), None # yield a fasta record
            if not last: break
        else: # this is a fastq record
            seq, leng, seqs = ''.join(seqs), 0, []
            for l in fp: # read the quality
                seqs.append(l[:-1])
                leng += len(l) - 1
                if leng >= len(seq): # have read enough quality
                    last = None
                    yield name, seq, ''.join(seqs); # yield a fastq record
                    break
            if last: # reach EOF before reading enough quality
                yield name, seq, None # yield a fasta record instead
                break

def generate_strobemer_sequence(seq, p1, p2, p3, k_size):
    # make sure index is not out of range
    #if any(p < 0 or p + k_size > len(seq) for p in [p1, p2, p3]):
    #    raise ValueError("p1, p2, p3 和 k_size are out of index")

    strobe1 = seq[p1:p1+k_size]
    strobe2 = seq[p2:p2+k_size]
    strobe3 = seq[p3:p3+k_size]

    strobemer = strobe1 + '-' + strobe2 + '-' +  strobe3

    return strobemer


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description = "This is the script to test the strobmers by python from https://github.com/ksahlin/strobemers")
    parser.add_argument('-i', '--input', required = True, help = 'Input your fastq')
    parser.add_argument('-f', '--format', required = True, help = 'The data format extension of your input, e.g.: fasta, fastq, fastq.gz')
    args = parser.parse_args()
    inputfile = args.input
    form = args.format
    n, slen, qlen = 0, 0, 0
    all_mers = defaultdict(list)
    k_size = 12
    w_min = 10
    w_max = 100
    w = 100

    if form == 'gz':
        with gzip.open(inputfile, 'rt') as fp:
            for name, seq, qual in readfq(fp):
                for (p1,p2,p3), h in indexing.randstrobes(seq, k_size, w_min, w_max, w =60 , order = 3).items():
                # all_mers is a dictionary with hash values as keys and
                # a list with position-tuples of where the strobemer is sampled from
                    all_mers[h].append( (p1,p2,p3) )
    else:
        with open(inputfile, "rt") as fp:
            for name, seq, qual in readfq(fp):
                print(name)
                print(seq)
                # Order = 2
                #for (p1,p2), s in indexing.randstrobes_iter(seq, k_size, w_min, w_max, w = w,order = 2, buffer_size = 1000000):
                #    print((s, p1,p2))
                #    all_mers[s].append( (p1,p2) )
                # Order = 3
                for (p1,p2,p3), h in indexing.randstrobes(seq, k_size, w_min, w_max, w = 60, order = 3).items():
                    sequence = generate_strobemer_sequence(seq, p1, p2, p3, k_size)
                    print((h, p1, p2, p3, sequence))
                    all_mers[h].append( (p1,p2,p3, sequence) )

```

**Comment by ksahlin** [comment]
I don't know what your aim is. Why can't you use a ready made aligner like [strobealign](https://github.com/ksahlin/strobealign)? 

There is also a Python version of Strobemap here: https://github.com/ksahlin/strobemers/blob/main/StrobeMap_Maier

**Comment by yaowei2010** [comment]
OK Thank you for your suggestion!
