### ISSUE TITLE
How to adjust the searching window for positions near the end of the sequence

### ISSUE THREAD

**Issue by shenwei356** [ksahlin/strobemers#2]
Hi, I'm a little confused about how to adjust the searching window for positions near the end of the sequence.

I know that these positions need to be kept for producing an equal number of strobemers as k-mers. But in sequence mapping/searching scenarios, unlike k-mers, the strobemers near the end of the sequences would be different from these in the reference sequence, because of the incomplete searching window.

In the function `seq_to_randstrobes2_iter`:

    window_p_start = p + strobe_w_min_offset if p + strobe_w_max_offset <= len(hash_seq_list) else max( (p + strobe_w_min_offset) -  (p + strobe_w_max_offset - len(hash_seq_list)), p )
    window_p_end = min(p + strobe_w_max_offset, len(hash_seq_list))

For positions near the end of the sequence (`p + strobe_w_max_offset > len(hash_seq_list)`),

    max( (p + strobe_w_min_offset) -  (p + strobe_w_max_offset - len(hash_seq_list)), p )

equals to 

    max( len(hash_seq_list) - (strobe_w_max_offset - strobe_w_in_offset), p)

As I understand, it *keeps the size of the searching window and moves the window to the left* (box A in the figure below), am I right? Have you tried the way in box B?

![Screenshot_20210413_230241](https://user-images.githubusercontent.com/2655946/114575092-7075ac00-9cac-11eb-9336-065682e3ae15.png)

Besides, for order 3, the windows of `m2` and `m3` would have some duplicated regions, is this OK?

![Screenshot_20210413_230706](https://user-images.githubusercontent.com/2655946/114575671-fc87d380-9cac-11eb-8252-6d6f1db3925b.png)

**Comment by shenwei356** [comment]
For computing the searching window of m2, I'm not sure if there's a bug.

https://github.com/ksahlin/strobemers/blob/main/modules/indexing.py#L189

    window_p1_start = p + strobe_w_min_offset if p + 2*strobe_w_max_offset <= len(hash_seq_list) else max(p,  len(hash_seq_list)  + 2*(strobe_w_min_offset - strobe_w_max_offset))

Does the condition `if p + 2*strobe_w_max_offset <= len(hash_seq_list)` should be `if p + strobe_w_max_offset <= len(hash_seq_list)`.

**Comment by shenwei356** [comment]
My brain is down, would you please help to mark the correct windows in the [illustration.xlsx](https://github.com/shenwei356/strobemers/blob/main/illustration.xlsx?raw=true). Thank you so much.

**Comment by ksahlin** [comment]
Hehe sure. Overall I don't know if it matters much, but nevertheless, it is good to be consistent.
 
I implemented alternative A in your first illustration (up to any offset bugs that you may find). That is, first the offset (w_min) decreases, then the window gets narrower at the very end. 

For three or more, I implemented (and suggested in the paper) to scale down all _segments_ equally with floor operator. With a "segment" here, I mean the range between the previous w_max to current w_max (i.e., a segment is w_max bases). 

In practice, this leads to what I've drawn out in the figure below in the highlighted box. Note that as soon as there are not sufficient room, all the windows are divided.

However, a final remark. If all this "extra checking" is detrimental to runtime, I think speed should be prioritized. One could consider stopping to generate strobemers whenever when one needs rescaling (or any other heuristic solution)

![Screen Shot 2021-04-13 at 7 01 06 PM](https://user-images.githubusercontent.com/1714667/114591869-9ee28f80-9c8a-11eb-8cb8-a61ca1e0cba2.png)

**Comment by shenwei356** [comment]
Thank you for the details.

**Comment by ksahlin** [comment]
@shenwei356 - It is amazing how I missed your main concern in this issue: "_the strobemers near the end of the sequences would be different from these in the reference sequence, because of the incomplete searching window._", which can matter a lot for short sequences. This is a very good point that was also just raised by another user @lutfia95 which made me revisit this.  

My opinion is now that one should pick whichever strategy that maximizes potential matches in the end, or alternatively stop before any modification is needed. Given this, your strategy B would be preferable.

Thanks for pointing this out and sorry for my initial answer which is not a good answer for read mapping applications.
