### ISSUE TITLE
Identical fasta headers between query and reference yield no matches

### ISSUE THREAD

**Issue by moorembioinfo** [ksahlin/strobemers#6]
Hi, 

I've noticed with StrobeMap (python) that if contig fasta headers are identical between the query and the reference it will return no matches. This might be a problem as contig fasta headers are often unspecific (>contig1, >contig2 etc.)

Thanks and best regards, 

Matt

**Comment by ksahlin** [comment]
Hi Matt,

you can specify `--selfalign` to force alignment between identical query and reference names.

Best,
K
